import { PATCH_VERSION } from "./patch.js";

// Factory patches. Cables are written "module.port → module.port" for readability.
function patch({ bpm, swing = 0, modules, cables }) {
  return {
    v: PATCH_VERSION,
    bpm,
    swing,
    modules: modules.map(([id, type, values = {}, data]) => ({
      id,
      type,
      values,
      ...(data && { data }),
    })),
    cables: cables.map((line) => {
      const [from, to] = line.split("→").map((end) => end.trim().split("."));
      return [from[0], from[1], to[0], to[1]];
    }),
  };
}

const nightDrive = patch({
  bpm: 124,
  swing: 0.2,
  modules: [
    ["grid", "grid", { drift: 0.2 }],
    [
      "steps",
      "steps",
      { octave: -1, gate: 0.45, glide: 0.07, scale: "minor", root: "A" },
    ],
    [
      "turing",
      "turing",
      { chaos: 0.04, rate: "1/8", range: 9, scale: "pent min", root: "A" },
    ],
    ["euclid", "euclid", { stepsa: 16, hitsa: 5, rota: 2 }],
    ["env", "env", { attack: 0.002, decay: 0.2, sustain: 0.05, release: 0.1 }],
    ["lfo", "lfo", { sync: "4 bar", depth: 3 }],
    ["kit", "kit", { kickTune: 46, kickDecay: 0.55, punch: 0.65 }],
    ["vco", "vco", { octave: -1, wave: "sawtooth", drift: 0.2 }],
    ["vcf", "vcf", { cutoff: 260, res: 17, amount: 0.62, drive: 0.45 }],
    ["vca", "vca"],
    ["dirt", "dirt", { drive: 0.3, bits: 10, rate: 1, mix: 0.35, tone: 7000 }],
    ["string", "string", { tune: 0, bright: 0.62, decay: 0.82, body: 0.4 }],
    [
      "fold",
      "fold",
      { octave: -1, ratio: 1.5, index: 0.5, fold: 0.3, level: 0.55 },
    ],
    ["lpg", "lpg", { decay: 0.28, res: 0.45 }],
    ["tape", "tape", { sync: "3/16", feedback: 0.52, mix: 0.45, wow: 0.35 }],
    ["space", "space", { size: 3.6, mix: 0.55, damp: 4200 }],
    ["mix", "mix", { a: 0.95, b: 0.55, c: 0.5, d: 0.6 }],
    ["scope", "scope", { zoom: 0.3 }],
    ["out", "out", { level: 0.85 }],
  ],
  cables: [
    "grid.kick → kit.kick",
    "grid.snare → kit.snare",
    "grid.hat → kit.hat",
    "grid.open → kit.open",
    "grid.clap → kit.clap",
    "grid.zap → kit.zap",
    "steps.pitch → vco.pitch",
    "steps.gate → env.gate",
    "vco.out → vcf.in",
    "env.out → vcf.cutoff",
    "vcf.out → vca.in",
    "env.out → vca.cv",
    "vca.out → dirt.in",
    "turing.pitch → string.pitch",
    "turing.gate → string.pluck",
    "string.out → tape.in",
    "turing.pitch → fold.pitch",
    "lfo.out → fold.index",
    "fold.out → lpg.in",
    "euclid.a → lpg.strike",
    "lpg.out → space.in",
    "kit.out → mix.a",
    "dirt.out → mix.b",
    "tape.out → mix.c",
    "space.out → mix.d",
    "mix.out → scope.a",
    "env.out → scope.b",
    "scope.thru → out.left",
  ],
});

const westCoast = patch({
  bpm: 92,
  swing: 0.12,
  modules: [
    [
      "euclid",
      "euclid",
      {
        stepsa: 16,
        hitsa: 7,
        rota: 0,
        stepsb: 12,
        hitsb: 5,
        rotb: 3,
        stepsc: 9,
        hitsc: 2,
        rotc: 1,
      },
    ],
    [
      "turing",
      "turing",
      {
        chaos: 0.12,
        length: 11,
        rate: "1/8",
        range: 10,
        scale: "hirajoshi",
        root: "D",
      },
    ],
    ["lfo", "lfo", { sync: "1 bar", depth: 2.2, wave: "triangle" }],
    ["quant", "quant", { scale: "hirajoshi", root: "D" }],
    ["lfo2", "lfo", { rate: 0.07, depth: 4, wave: "sine" }],
    [
      "fold",
      "fold",
      { octave: -1, ratio: 2.01, index: 0.9, fold: 0.45, level: 0.7 },
    ],
    [
      "fold2",
      "fold",
      { octave: -2, ratio: 3.5, index: 0.4, fold: 0.6, level: 0.6 },
    ],
    ["lpg", "lpg", { decay: 0.45, res: 0.5 }],
    ["lpg2", "lpg", { decay: 0.9, res: 0.2 }],
    ["string", "string", { tune: 1, bright: 0.8, decay: 0.9, body: 0.7 }],
    ["mix", "mix", { a: 0.9, b: 0.7, c: 0.45, d: 0 }],
    [
      "tape",
      "tape",
      { sync: "3/8", feedback: 0.62, mix: 0.4, wow: 0.55, tone: 1800 },
    ],
    ["space", "space", { size: 6.5, mix: 0.5, damp: 3000, pre: 0.06 }],
    ["scope", "scope", { mode: "xy", gainB: 1 }],
    ["out", "out", { level: 0.9 }],
  ],
  cables: [
    "turing.pitch → fold.pitch",
    "turing.mod → fold.fold",
    "euclid.a → lpg.strike",
    "fold.out → lpg.in",
    "lfo2.out → quant.in",
    "quant.out → fold2.pitch",
    "lfo.out → fold2.index",
    "euclid.b → lpg2.strike",
    "fold2.out → lpg2.in",
    "turing.pitch → string.pitch",
    "euclid.c → string.pluck",
    "lpg.out → mix.a",
    "lpg2.out → mix.b",
    "string.out → mix.c",
    "mix.out → tape.in",
    "tape.out → space.in",
    "space.out → out.left",
    "lpg.out → scope.a",
    "lpg2.out → scope.b",
  ],
});

const resonantMachine = patch({
  bpm: 132,
  swing: 0.08,
  modules: [
    [
      "euclid",
      "euclid",
      {
        stepsa: 16,
        hitsa: 4,
        stepsb: 16,
        hitsb: 11,
        rotb: 1,
        stepsc: 5,
        hitsc: 2,
      },
    ],
    [
      "grid",
      "grid",
      { drift: 0.3 },
      {
        mutes: [false, false, false, false, false, false],
        lanes: [
          [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
          [0, 0, 0, 0, 1, 0, 0, 3, 0, 0, 0, 0, 1, 0, 3, 0],
          [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
          [0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0],
          [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
          [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        ],
      },
    ],
    [
      "steps",
      "steps",
      { octave: -2, rate: "1/8", scale: "phrygian", root: "E", gate: 0.4 },
      {
        steps: [
          { note: 0, mode: "accent" },
          { note: 0, mode: "on" },
          { note: 1, mode: "slide" },
          { note: 0, mode: "on" },
          { note: 7, mode: "ratchet" },
          { note: 0, mode: "off" },
          { note: 12, mode: "accent" },
          { note: 5, mode: "on" },
        ],
      },
    ],
    [
      "turing",
      "turing",
      {
        chaos: 0.02,
        length: 16,
        rate: "1/16",
        range: 14,
        scale: "phrygian",
        root: "E",
        octave: 0,
      },
    ],
    [
      "kit",
      "kit",
      {
        kickTune: 52,
        kickDecay: 0.35,
        punch: 0.9,
        zapTune: 900,
        color: 0.8,
        hatDecay: 0.03,
      },
    ],
    ["string", "string", { tune: -1, bright: 0.4, decay: 0.95, body: 0.3 }],
    ["vco", "vco", { octave: 0, wave: "square", drift: 0.1 }],
    ["lpg", "lpg", { decay: 0.22, res: 0.7 }],
    ["dirt", "dirt", { drive: 0.7, bits: 6, rate: 3, tone: 3500, mix: 0.55 }],
    ["mix", "mix", { a: 0.9, b: 0.8, c: 0.7, d: 0 }],
    ["tape", "tape", { sync: "1/8", feedback: 0.35, mix: 0.25 }],
    ["space", "space", { size: 1.4, mix: 0.2 }],
    ["scope", "scope"],
    ["out", "out"],
  ],
  cables: [
    "euclid.a → kit.kick",
    "euclid.b → kit.hat",
    "euclid.c → kit.zap",
    "grid.snare → kit.snare",
    "grid.open → kit.open",
    "grid.clap → kit.clap",
    "kit.out → string.excite",
    "turing.pitch → string.pitch",
    "steps.pitch → vco.pitch",
    "steps.gate → lpg.strike",
    "vco.out → lpg.in",
    "lpg.out → dirt.in",
    "kit.out → mix.a",
    "string.out → mix.b",
    "dirt.out → mix.c",
    "mix.out → tape.in",
    "tape.out → space.in",
    "space.out → scope.a",
    "scope.thru → out.left",
  ],
});

const playMe = patch({
  bpm: 110,
  modules: [
    ["keys", "keys", { glide: 0.02 }],
    ["env", "env", { attack: 0.01, decay: 0.4, sustain: 0.6, release: 0.8 }],
    ["lfo", "lfo", { rate: 0.3, depth: 1.5 }],
    ["vco", "vco", { octave: 0, wave: "sawtooth", fmAmt: 0.05 }],
    [
      "fold",
      "fold",
      { octave: 0, ratio: 1, index: 0.2, fold: 0.2, level: 0.4 },
    ],
    ["string", "string", { tune: 0, bright: 0.7, decay: 0.85 }],
    ["mix", "mix", { a: 0.7, b: 0.5, c: 0.6, d: 0 }],
    ["vcf", "vcf", { cutoff: 900, res: 5, amount: 0.7, slope: "12dB" }],
    ["vca", "vca"],
    ["tape", "tape", { sync: "1/4", feedback: 0.4, mix: 0.3 }],
    ["space", "space", { size: 4, mix: 0.4 }],
    ["scope", "scope"],
    ["out", "out"],
  ],
  cables: [
    "keys.pitch → vco.pitch",
    "keys.pitch → fold.pitch",
    "keys.pitch → string.pitch",
    "keys.gate → env.gate",
    "keys.gate → string.pluck",
    "lfo.out → vco.fm",
    "vco.out → mix.a",
    "fold.out → mix.b",
    "mix.out → vcf.in",
    "env.out → vcf.cutoff",
    "vcf.out → vca.in",
    "env.out → vca.cv",
    "string.out → mix.c",
    "vca.out → tape.in",
    "tape.out → space.in",
    "space.out → scope.a",
    "scope.thru → out.left",
  ],
});

export const presets = [
  {
    id: "night-drive",
    name: "Night Drive",
    blurb: "Acid bass, swung drums, plucked strings and bongo echoes",
    patch: nightDrive,
  },
  {
    id: "west-coast",
    name: "West Coast Ritual",
    blurb: "Wavefolded bongos in odd meters, no drums, lots of space",
    patch: westCoast,
  },
  {
    id: "resonant",
    name: "Resonant Machine",
    blurb: "Euclid drums ringing a tuned string, crushed square bass",
    patch: resonantMachine,
  },
  {
    id: "play-me",
    name: "Play Me",
    blurb: "A keyboard voice: play with MIDI or A–K on your keyboard",
    patch: playMe,
  },
];
